// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "app": {
    "App": {
      /**
       * GetConfig
       * @returns {Promise<Config>}  - Go Type: config.Config
       */
      "GetConfig": () => {
        return window.go.app.App.GetConfig();
      },
      /**
       * GetMessageContent
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<EmailContent|Error>}  - Go Type: email.EmailContent
       */
      "GetMessageContent": (arg1) => {
        return window.go.app.App.GetMessageContent(arg1);
      },
      /**
       * GetMessages
       * @returns {Promise<Array<Message>|Error>}  - Go Type: []database.Message
       */
      "GetMessages": () => {
        return window.go.app.App.GetMessages();
      },
      /**
       * GetThreads
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<Array<Thread>|Error>}  - Go Type: []database.Thread
       */
      "GetThreads": (arg1) => {
        return window.go.app.App.GetThreads(arg1);
      },
      /**
       * ReadThread
       * @param {number} arg1 - Go Type: int
       * @returns {Promise<Array<Message>|Error>}  - Go Type: []database.Message
       */
      "ReadThread": (arg1) => {
        return window.go.app.App.ReadThread(arg1);
      },
      /**
       * TagThread
       * @param {number} arg1 - Go Type: int
       * @param {string} arg2 - Go Type: string
       * @returns {Promise<Thread|Error>}  - Go Type: database.Thread
       */
      "TagThread": (arg1, arg2) => {
        return window.go.app.App.TagThread(arg1, arg2);
      },
    },
  },

};
export default go;
