// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
window.wailsbindings = {"app":{"App":{"GetConfig":{"name":"app.App.GetConfig","outputs":[{"type":"config.Config"}]},"GetMessageContent":{"name":"app.App.GetMessageContent","inputs":[{"type":"string"}],"outputs":[{"type":"email.EmailContent"},{"type":"error"}]},"GetMessages":{"name":"app.App.GetMessages","outputs":[{"type":"[]database.Message"},{"type":"error"}]},"GetThreads":{"name":"app.App.GetThreads","inputs":[{"type":"string"}],"outputs":[{"type":"[]database.Thread"},{"type":"error"}]},"ReadThread":{"name":"app.App.ReadThread","inputs":[{"type":"int"}],"outputs":[{"type":"[]database.Message"},{"type":"error"}]},"TagQuery":{"name":"app.App.TagQuery","inputs":[{"type":"string"},{"type":"string"}],"outputs":[{"type":"error"}]},"TagThread":{"name":"app.App.TagThread","inputs":[{"type":"int"},{"type":"string"}],"outputs":[{"type":"database.Thread"},{"type":"error"}]},"Update":{"name":"app.App.Update","outputs":[{"type":"error"}]}}}};
const go = {
  "app": {
    "App": {
      /**
       * GetConfig
       * @returns {Promise<Config>}  - Go Type: config.Config
       */
      "GetConfig": () => {
        return window.go.app.App.GetConfig();
      },
      /**
       * GetMessageContent
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<EmailContent|Error>}  - Go Type: email.EmailContent
       */
      "GetMessageContent": (arg1) => {
        return window.go.app.App.GetMessageContent(arg1);
      },
      /**
       * GetMessages
       * @returns {Promise<Array<Message>|Error>}  - Go Type: []database.Message
       */
      "GetMessages": () => {
        return window.go.app.App.GetMessages();
      },
      /**
       * GetThreads
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<Array<Thread>|Error>}  - Go Type: []database.Thread
       */
      "GetThreads": (arg1) => {
        return window.go.app.App.GetThreads(arg1);
      },
      /**
       * ReadThread
       * @param {number} arg1 - Go Type: int
       * @returns {Promise<Array<Message>|Error>}  - Go Type: []database.Message
       */
      "ReadThread": (arg1) => {
        return window.go.app.App.ReadThread(arg1);
      },
      /**
       * TagQuery
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @returns {Promise<Error>}  - Go Type: error
       */
      "TagQuery": (arg1, arg2) => {
        return window.go.app.App.TagQuery(arg1, arg2);
      },
      /**
       * TagThread
       * @param {number} arg1 - Go Type: int
       * @param {string} arg2 - Go Type: string
       * @returns {Promise<Thread|Error>}  - Go Type: database.Thread
       */
      "TagThread": (arg1, arg2) => {
        return window.go.app.App.TagThread(arg1, arg2);
      },
      /**
       * Update
       * @returns {Promise<Error>}  - Go Type: error
       */
      "Update": () => {
        return window.go.app.App.Update();
      },
    },
  },

};
export default go;
